ObvyHomeLibrary/ObvyHomeLibrary.WebApp/Models/ErrorViewModel.cs
using System;

namespace ObvyHomeLibrary.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ObvyHomeLibrary/ObvyHomeLibrary.WebApp/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ObvyHomeLibrary.BookDetailsService.Contract.Dto;
using ObvyHomeLibrary.BookDetailsService.Contract.Service;
using ObvyHomeLibrary.BookStoreService.Contract.Dto;
using ObvyHomeLibrary.BookStoreService.Contract.Model;
using ObvyHomeLibrary.BookStoreService.Contract.Service;
using ObvyHomeLibrary.WebApp.Dto;
using ObvyHomeLibrary.WebApp.Models;

namespace ObvyHomeLibrary.WebApp.Controllers
{
    public class BookController : Controller
    {
        private const string LastSearchedBookDetailsSessionKey = "LastSearchedBookDetails";

        private readonly IBookDetailsService _bookDetailsService;
        private readonly IBookStoreService _bookStoreService;

        public BookController(IBookDetailsService bookDetailsService, IBookStoreService bookStoreService)
        {
            _bookDetailsService = bookDetailsService;
            _bookStoreService = bookStoreService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetData(string isbnCode)
        {
            try
            {
                Regex isbnRegex = new Regex(@"\D");
                string filteredIsbnCode = isbnRegex.Replace(isbnCode, string.Empty);

                BookDetails bookDetails = await _bookDetailsService.GetBookDetailsAsync(filteredIsbnCode);

                if (bookDetails == null)
                {
                    return Json(null);
                }

                await HttpContext.Session.LoadAsync();
                string bookDetailsJson = JsonConvert.SerializeObject(bookDetails);
                HttpContext.Session.SetString(LastSearchedBookDetailsSessionKey, bookDetailsJson);
                await HttpContext.Session.CommitAsync();

                BookDto bookDto = new BookDto(bookDetails);
                return Json(bookDto);
            }

            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Add()
        {
            try
            {
                await HttpContext.Session.LoadAsync();
                string bookDetailsJson = HttpContext.Session.GetString(LastSearchedBookDetailsSessionKey);
                if (string.IsNullOrEmpty(bookDetailsJson))
                {
                    throw new Exception($"Impossible to find the book to add.");
                }

                BookDetails bookDetails = JsonConvert.DeserializeObject<BookDetails>(bookDetailsJson);
                Book book = new Book
                {
                    Isbn10 = bookDetails.Isbn10,
                    Isbn13 = bookDetails.Isbn13,
                    Title = bookDetails.Title,
                    Author = bookDetails.Author,
                    Genre = bookDetails.Genre
                };
                await _bookStoreService.AddBookToStoreAsync(book);

            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
            return Json(null);
        }

        [HttpPost]
        public async Task<IActionResult> Search(BookSearchQuery searchQuery)
        {
            try
            {
                BookSearchResult searchResult = await _bookStoreService.SearchBooksAsync(searchQuery);
                IEnumerable<BookDto> bookDtoList = searchResult?.Books?.Select(b => new BookDto(b));
                return Json(bookDtoList);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(long id)
        {
            try
            {
                Book book = await _bookStoreService.GetBookAsync(id);
                BookDto bookDto = book != null ? new BookDto(book) : null;
                return Json(bookDto);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Lend(LendBookDto lendBookDto)
        {
            try
            {
                await _bookStoreService.LendBookAsync(lendBookDto.Id, lendBookDto.BorrowName, lendBookDto.BorrowComment);
                return Json(null);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Recover(long id)
        {
            try
            {
                await _bookStoreService.RecoverBookAsync(id);
                return Json(null);
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

ObvyHomeLibrary/ObvyHomeLibrary.WebApp/Views/Book/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Obvy Home Library</h2>

<h4>Add new book</h4>
<table class="table-condensed">
    <tr>
        <td>ISBN (10 or 13)</td>
        <td><input type="text" id="searchDataIsbnCodeTextbox" maxlength="13" onkeyup="filterNotNumChar(event);" /></td>
        <td><input type="button" value="Find book by ISBN" onclick="getData();" /></td>
    </tr>
</table>
<div id="searchDataResult" style="display: none;">
    <table class="table-condensed">
        <tr>
            <th>ISBN 10</th>
            <td><span id="dataIsbn10"></span></td>
        </tr>
        <tr>
            <th>ISBN 13</th>
            <td><span id="dataIsbn13"></span></td>
        </tr>
        <tr>
            <th>Title</th>
            <td><span id="dataTitle"></span></td>
        </tr>
        <tr>
            <th>Author</th>
            <td><span id="dataAuthor"></span></td>
        </tr>
        <tr>
            <th>Genre</th>
            <td><span id="dataGenre"></span></td>
        </tr>
        <tr>
            <td colspan="2"><input type="button" value="Add to the store" onclick="add();" /></td>
        </tr>
    </table>
</div>

<h4>Search book store</h4>
<table class="table-condensed text-nowrap">
    <tr>
        <td>ISBN 10</td>
        <td><input type="text" id="searchIsbn10Textbox" /></td>
        <td>ISBN 13</td>
        <td><input type="text" id="searchIsbn13Textbox" /></td>
        <td>Title</td>
        <td><input type="text" id="searchTitleTextbox" /></td>
        <td>Author</td>
        <td><input type="text" id="searchAuthorTextbox" /></td>
        <td>Genre</td>
        <td><input type="text" id="searchGenreTextbox" /></td>
        <td><input type="button" value="Search" onclick="search();" /></td>
    </tr>
</table>
<table class="table table-condensed table-striped" id="searchResultsTable" style="display: none;">
    <thead>
        <tr>
            <th>ISBN 10</th>
            <th>ISBN 13</th>
            <th>Title</th>
            <th>Author</th>
            <th>Genre</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="searchResultsBody"></tbody>
</table>

<div id="details" style="display: none;">
    <h4>Book details</h4>
    <input type="hidden" id="detailsIdHidden" />
    <table class="table-condensed">
        <tr>
            <th>ISBN 10</th>
            <td><span id="detailsIsbn10"></span></td>
        </tr>
        <tr>
            <th>ISBN 13</th>
            <td><span id="detailsIsbn13"></span></td>
        </tr>
        <tr>
            <th>Title</th>
            <td><span id="detailsTitle"></span></td>
        </tr>
        <tr>
            <th>Author</th>
            <td><span id="detailsAuthor"></span></td>
        </tr>
        <tr>
            <th>Genre</th>
            <td><span id="detailsGenre"></span></td>
        </tr>
    </table>
    <table class="table-condensed" id="detailsIsBorrowedTable" style="display: none;">
        <tr>
            <th>Borrowed by</th>
            <td><span id="detailsBorrowName"></span></td>
        </tr>
        <tr>
            <th>Borrow date / time</th>
            <td><span id="detailsBorrowDate"></span>&nbsp;<span id="detailsBorrowTime"></span></td>
        </tr>
        <tr>
            <th>Borrow comment</th>
            <td><span id="detailsBorrowComment"></span></td>
        </tr>
        <tr>
            <td colspan="2"><input type="button" value="Recover the book" onclick="recover();" /></td>
        </tr>
    </table>
    <table class="table-condensed" id="detailsIsNotBorrowedTable" style="display: none;">
        <tr>
            <th>Lend to</th>
            <td><input type="text" id="detailsBorrowNameTextbox" /></td>
        </tr>
        <tr>
            <th>Comment</th>
            <td><input type="text" id="detailsBorrowCommentTextbox" /></td>
        </tr>
        <tr>
            <td colspan="2"><input type="button" value="Lend the book" onclick="lend();" /></td>
        </tr>
    </table>
</div>

<h4>History</h4>
<table class="table table-condensed">
    <thead>
        <tr>
            <th class="col-xs-1">Time</th>
            <th>Message</th>
        </tr>
    </thead>
    <tbody id="messagesHistoryBody"></tbody>
</table>

ObvyHomeLibrary/ObvyHomeLibrary.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Obvy Home Library</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Book" asp-action="Index" class="navbar-brand">Obvy Home Library</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Guillaume Fernandez</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>